name: 'Setup Dojo and Scarb'
description: 'Install and cache Dojo and Scarb toolchain'
inputs:
  dojo-version:
    description: 'Dojo version to install'
    required: false
    default: 'v1.5.0-alpha.2'
  scarb-version:
    description: 'Scarb version to install'
    required: false
    default: '2.10.1'

runs:
  using: "composite"
  steps:
    - name: Cache Dojo installation
      uses: actions/cache@v4
      id: cache-dojo
      with:
        path: |
          ~/.config/.dojo
        key: ${{ runner.os }}-dojo-${{ inputs.dojo-version }}
    
    - name: Install Dojo
      if: steps.cache-dojo.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -L https://install.dojoengine.org | bash
        /home/runner/.config/.dojo/dojoup/dojoup install ${{ inputs.dojo-version }}
    
    - name: Setup Scarb with cache
      uses: software-mansion/setup-scarb@v1
      with:
        scarb-version: ${{ inputs.scarb-version }}
    
    - name: Add Dojo to PATH
      shell: bash
      run: echo "/home/runner/.config/.dojo/bin" >> $GITHUB_PATH