name: "Setup Dojo and Scarb"
description: "Install and cache Dojo and Scarb toolchain"
inputs:
  dojo-version:
    description: "Dojo version to install"
    required: false
    default: "v1.7.2"
  scarb-version:
    description: "Scarb version to install"
    required: false
    default: "2.12.2"

runs:
  using: "composite"
  steps:
    - name: Cache Dojo installation
      uses: actions/cache@v4
      id: cache-dojo
      with:
        path: |
          ~/.config/.dojo
        key: ${{ runner.os }}-dojo-${{ inputs.dojo-version }}

    - uses: software-mansion/setup-scarb@v1
      with:
        scarb-version: ${{ inputs.scarb-version }}

    - name: Install dojo
      run: |
        curl -L -o dojo-linux-x86_64.tar.gz https://github.com/dojoengine/dojo/releases/download/${{ inputs.dojo-version }}/dojo_${{ inputs.dojo-version }}_linux_amd64.tar.gz
        tar -xzf dojo-linux-x86_64.tar.gz
        sudo mv sozo /usr/local/bin/
      shell: bash
