packages:
  - "packages/*"
  - "examples/**"

catalog:
  starknet: ^8.1.2
  "@starknet-io/get-starknet-core": 4.0.7
  "@starknet-react/core": ^4.0.1-beta.4
  "@starknet-react/chains": ^4.0.1-beta.3
  "@starknet-io/types-js": ^0.8
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1
  react: ^18.3.1
  react-dom: ^18.3.1
