packages:
  - "packages/*"
  - "examples/**"

catalog:
  starknet: 7.1.0
  "@starknet-io/get-starknet-core": 4.0.7
  "@starknet-react/core": ^3.6.2
  "@starknet-react/chains": ^3.1.0
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1
  react: ^18.3.1
  react-dom: ^18.3.1
