/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
    return {
        Energy: (() => {
            return defineComponent(
                world,
                { id: RecsType.Number, amt: RecsType.Number },
                {
                    metadata: {
                        name: "Energy",
                        types: [],
                    },
                }
            );
        })(),
        GameData: (() => {
            return defineComponent(
                world,
                {
                    game: RecsType.Number,
                    number_of_players: RecsType.Number,
                    available_ids: RecsType.NumberArray,
                },
                {
                    metadata: {
                        name: "GameData",
                        types: [],
                    },
                }
            );
        })(),
        PlayerID: (() => {
            return defineComponent(
                world,
                { player: RecsType.String, id: RecsType.Number },
                {
                    metadata: {
                        name: "PlayerID",
                        types: [],
                    },
                }
            );
        })(),
        Position: (() => {
            return defineComponent(
                world,
                { id: RecsType.Number, x: RecsType.Number, y: RecsType.Number },
                {
                    metadata: {
                        name: "Position",
                        types: [],
                    },
                }
            );
        })(),
        RPSType: (() => {
            return defineComponent(
                world,
                { id: RecsType.Number, rps: RecsType.Number },
                {
                    metadata: {
                        name: "RPSType",
                        types: [],
                    },
                }
            );
        })(),
    };
}
