/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
    return {
        GameData: (() => {
            return defineComponent(
                world,
                {
                    game: RecsType.Number,
                    number_of_players: RecsType.Number,
                    available_ids: RecsType.NumberArray,
                },
                {
                    metadata: {
                        name: "GameData",
                        types: [],
                    },
                }
            );
        })(),
        MovesQueue: (() => {
            return defineComponent(
                world,
                {
                    player: RecsType.String,
                    m1: RecsType.Number,
                    m2: RecsType.Number,
                    m3: RecsType.Number,
                },
                {
                    metadata: {
                        name: "MovesQueue",
                        types: ["Direction", "Direction", "Direction"],
                    },
                }
            );
        })(),
        Player: (() => {
            return defineComponent(
                world,
                {
                    id: RecsType.Number,
                    player: RecsType.String,
                    position: { x: RecsType.Number, y: RecsType.Number },
                    energy: RecsType.Number,
                    rps: RecsType.Number,
                },
                {
                    metadata: {
                        name: "Player",
                        types: ["Vec2"],
                    },
                }
            );
        })(),
        PlayerID: (() => {
            return defineComponent(
                world,
                { player: RecsType.String, id: RecsType.Number },
                {
                    metadata: {
                        name: "PlayerID",
                        types: [],
                    },
                }
            );
        })(),
    };
}
