[workspace]

[package]
edition = "2021"
name = "torii-client-wasm"
version = "0.3.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
async-std = { version = "1.12.0", default-features = false, features = [ "std" ] }
async-trait = "0.1.68"
futures = "0.3.28"
parking_lot = "0.12.1"
serde = { version = "1.0.156", features = [ "derive" ] }
serde_json = "1.0.64"
starknet = "0.6.0"
thiserror = "1.0.32"
tokio = { version = "1.32.0", default-features = false, features = [ "rt" ] }
url = "2.4.0"

# Dojo
dojo-types = { git = "https://github.com/dojoengine/dojo", branch = "main" }
torii-client = { git = "https://github.com/dojoengine/dojo", branch = "main" }

# WASM
js-sys = "0.3.64"
serde-wasm-bindgen = "0.6.0"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.4", features = [ 'MessageEvent', 'Window', 'Worker', 'WorkerGlobalScope', 'console' ] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
tsify = "0.4.5"

# Compiler optimization when running test to prevent ‘locals exceed maximum’ error, 
# where a function is using more that the maximum allowed local variables.
[profile.dev]
incremental = true
opt-level = 1

[dev-dependencies]
wasm-bindgen-test = "0.3.0"

[features]
console-error-panic = [ "dep:console_error_panic_hook" ]
